import type { Project } from "@/lib/domain";

export const sampleProject: Project = {
  id: "project-seiren-order-in",
  processId: "SRSN001",
  name: "Seiren Trading Order Intake",
  description:
    "Acquire TSV purchase order files from SharePoint, validate and transform them, then post order data to ServiceNow with evidence and error file handling.",
  sourceSystem: "SharePoint",
  destinationSystem: "ServiceNow",
  status: "Mapping Review",
  owner: "Boomi Architecture Team",
  schedule: "Mon-Fri 14:00 and 16:30",
  lastExportedAt: "2026-05-20T09:00:00.000Z",
  endpoints: [
    {
      id: "ep-sharepoint",
      name: "SharePoint PO folder",
      role: "source",
      connectorType: "HTTP Client / Microsoft Graph",
      profileType: "Flat File",
      format: "TSV input, CSV output",
      purpose: "Receive order TSV files, archive source files, and write evidence/error CSV files.",
      connectionInfo:
        "Site: SEIREN-NICCA; input: /DATA/PO/PO_SEIREN_*.tsv; archive: /DATA/PO/BAK; error: /DATA/PO/ERROR.",
    },
    {
      id: "ep-servicenow",
      name: "ServiceNow order staging",
      role: "destination",
      connectorType: "HTTP Client / REST API",
      profileType: "JSON",
      format: "JSON",
      purpose:
        "Post order data to staging table and query validation, import, and error statuses.",
      connectionInfo:
        "APIs: /table, /stats, /v1/batch; table: u_temp_edi_seiren_recieve.",
    },
    {
      id: "ep-mail",
      name: "Operational notification",
      role: "notification",
      connectorType: "Mail",
      profileType: "Message",
      format: "Text + CSV attachment",
      purpose: "Notify file-level failures and order-data validation failures.",
      connectionInfo:
        "From: system_notification@niccachemical.com; recipients vary by error class.",
    },
  ],
  profiles: [
    {
      id: "profile-source-po-tsv",
      name: "PO_SEIREN TSV",
      role: "source",
      type: "Flat File",
      format: "TSV",
      rootPath: "record",
      fields: [
        {
          id: "src-po-number",
          parentPath: "record",
          name: "購買伝票番号",
          label: "Purchase document number",
          description: "External PO number from Seiren order TSV.",
          dataType: "String",
          length: "15",
          required: true,
          keyField: true,
          format: "text",
          sample: "4500001234",
          ordinal: 1,
        },
        {
          id: "src-company-code",
          parentPath: "record",
          name: "会社コード",
          label: "Company code",
          dataType: "String",
          length: "4",
          required: true,
          keyField: false,
          sample: "3001",
          ordinal: 2,
        },
        {
          id: "src-document-date",
          parentPath: "record",
          name: "伝票日付",
          label: "Document date",
          dataType: "Date",
          length: "10",
          required: true,
          keyField: false,
          format: "yyyy/MM/dd",
          sample: "2026/05/20",
          ordinal: 3,
        },
        {
          id: "src-vendor-code",
          parentPath: "record",
          name: "仕入先コード",
          label: "Vendor code",
          dataType: "String",
          length: "10",
          required: true,
          keyField: false,
          ordinal: 4,
        },
        {
          id: "src-fax",
          parentPath: "record",
          name: "FAX番号",
          label: "Fax number",
          dataType: "String",
          length: "12",
          required: false,
          keyField: false,
          ordinal: 5,
        },
        {
          id: "src-line-no",
          parentPath: "record",
          name: "明細行",
          label: "Line number",
          dataType: "String",
          length: "3",
          required: true,
          keyField: true,
          ordinal: 6,
        },
        {
          id: "src-item-code",
          parentPath: "record",
          name: "品目コード",
          label: "Material code",
          dataType: "String",
          length: "18",
          required: true,
          keyField: false,
          ordinal: 7,
        },
        {
          id: "src-quantity",
          parentPath: "record",
          name: "発注数量",
          label: "Order quantity",
          dataType: "Decimal",
          length: "13,3",
          required: true,
          keyField: false,
          ordinal: 8,
        },
        {
          id: "src-delivery-date",
          parentPath: "record",
          name: "納期",
          label: "Delivery date",
          dataType: "Date",
          length: "10",
          required: false,
          keyField: false,
          format: "yyyy/MM/dd",
          ordinal: 9,
        },
      ],
    },
    {
      id: "profile-destination-servicenow",
      name: "ServiceNow u_temp_edi_seiren_recieve",
      role: "destination",
      type: "JSON",
      format: "JSON",
      rootPath: "$.records[*]",
      fields: [
        {
          id: "dst-u-po-no",
          parentPath: "$.records[*]",
          name: "u_purchase_document_no",
          label: "Purchase document number",
          dataType: "String",
          length: "15",
          required: true,
          keyField: true,
          ordinal: 1,
        },
        {
          id: "dst-u-company",
          parentPath: "$.records[*]",
          name: "u_company_code",
          label: "Company code",
          dataType: "String",
          length: "4",
          required: true,
          keyField: false,
          ordinal: 2,
        },
        {
          id: "dst-u-document-date",
          parentPath: "$.records[*]",
          name: "u_document_date",
          label: "Document date",
          dataType: "Date",
          length: "10",
          required: true,
          keyField: false,
          format: "yyyy-MM-dd",
          ordinal: 3,
        },
        {
          id: "dst-u-vendor",
          parentPath: "$.records[*]",
          name: "u_vendor_code",
          label: "Vendor code",
          dataType: "String",
          length: "10",
          required: true,
          keyField: false,
          ordinal: 4,
        },
        {
          id: "dst-u-order-source",
          parentPath: "$.records[*]",
          name: "u_order_source",
          label: "Order source",
          dataType: "String",
          length: "20",
          required: true,
          keyField: false,
          ordinal: 5,
        },
        {
          id: "dst-u-line-no",
          parentPath: "$.records[*]",
          name: "u_line_no",
          label: "Line number",
          dataType: "String",
          length: "3",
          required: true,
          keyField: true,
          ordinal: 6,
        },
        {
          id: "dst-u-item",
          parentPath: "$.records[*]",
          name: "u_item_code",
          label: "Material code",
          dataType: "String",
          length: "18",
          required: true,
          keyField: false,
          ordinal: 7,
        },
        {
          id: "dst-u-qty",
          parentPath: "$.records[*]",
          name: "u_order_quantity",
          label: "Order quantity",
          dataType: "Decimal",
          length: "13,3",
          required: true,
          keyField: false,
          ordinal: 8,
        },
        {
          id: "dst-u-delivery-date",
          parentPath: "$.records[*]",
          name: "u_delivery_date",
          label: "Delivery date",
          dataType: "Date",
          length: "10",
          required: false,
          keyField: false,
          format: "yyyy-MM-dd",
          ordinal: 9,
        },
      ],
    },
  ],
  mappingSets: [
    {
      id: "map-po-to-servicenow",
      name: "Seiren TSV to ServiceNow staging",
      sourceProfileId: "profile-source-po-tsv",
      destinationProfileId: "profile-destination-servicenow",
      direction: "inbound",
      status: "Ready for Boomi",
      rules: [
        {
          id: "rule-po-no",
          sourceFieldId: "src-po-number",
          destinationFieldId: "dst-u-po-no",
          mappingType: "direct",
          comment: "Primary external order key.",
          qualityStatus: "ok",
        },
        {
          id: "rule-company",
          sourceFieldId: "src-company-code",
          destinationFieldId: "dst-u-company",
          mappingType: "direct",
          comment: "Direct mapping from TSV company code.",
          qualityStatus: "ok",
        },
        {
          id: "rule-doc-date",
          sourceFieldId: "src-document-date",
          destinationFieldId: "dst-u-document-date",
          mappingType: "function",
          expression: "formatDate(伝票日付, 'yyyy/MM/dd', 'yyyy-MM-dd')",
          comment: "Boomi date formatting function required.",
          qualityStatus: "warning",
        },
        {
          id: "rule-vendor",
          sourceFieldId: "src-vendor-code",
          destinationFieldId: "dst-u-vendor",
          mappingType: "lookup",
          expression: "lookup(ServiceNow vendor conversion table)",
          comment: "Validate against vendor conversion master before posting.",
          qualityStatus: "warning",
        },
        {
          id: "rule-source",
          destinationFieldId: "dst-u-order-source",
          mappingType: "constant",
          defaultValue: "SEIREN",
          comment: "Fixed source label for downstream ServiceNow reporting.",
          qualityStatus: "ok",
        },
        {
          id: "rule-line",
          sourceFieldId: "src-line-no",
          destinationFieldId: "dst-u-line-no",
          mappingType: "direct",
          comment: "Line-level key with purchase document number.",
          qualityStatus: "ok",
        },
        {
          id: "rule-item",
          sourceFieldId: "src-item-code",
          destinationFieldId: "dst-u-item",
          mappingType: "lookup",
          expression: "lookup(Material conversion table)",
          comment: "Cross-reference material code before ServiceNow insert.",
          qualityStatus: "warning",
        },
        {
          id: "rule-qty",
          sourceFieldId: "src-quantity",
          destinationFieldId: "dst-u-qty",
          mappingType: "direct",
          comment: "Decimal precision must remain 13,3.",
          qualityStatus: "ok",
        },
        {
          id: "rule-delivery-date",
          sourceFieldId: "src-delivery-date",
          destinationFieldId: "dst-u-delivery-date",
          mappingType: "function",
          expression: "formatDate(納期, 'yyyy/MM/dd', 'yyyy-MM-dd')",
          comment: "Optional date. Leave null when source value is blank.",
          qualityStatus: "ok",
        },
      ],
      transformNodes: [
        {
          id: "node-date-format",
          label: "Normalize dates",
          nodeType: "format",
          config: { input: "yyyy/MM/dd", output: "yyyy-MM-dd" },
          position: { x: 420, y: 120 },
        },
        {
          id: "node-master-lookup",
          label: "Master lookups",
          nodeType: "lookup",
          config: { tables: "vendor, material" },
          position: { x: 420, y: 260 },
        },
      ],
    },
  ],
  processFlows: [
    {
      id: "flow-main",
      name: "Inbound order process",
      notes:
        "File-level errors stop the process and notify operations. Record-level errors are written to the error CSV and reported after ServiceNow validation.",
      nodes: [
        {
          id: "start",
          type: "start",
          label: "Scheduler",
          description: "Run on Boomi Process Scheduler.",
          position: { x: 0, y: 120 },
        },
        {
          id: "read-sharepoint",
          type: "connector",
          label: "Read TSV from SharePoint",
          description: "Fetch PO_SEIREN_*.tsv by Graph API.",
          position: { x: 230, y: 120 },
        },
        {
          id: "validate-file",
          type: "decision",
          label: "File checks",
          description: "Reject zero, multiple, or invalid-extension inputs.",
          position: { x: 480, y: 120 },
        },
        {
          id: "map-servicenow",
          type: "map",
          label: "Map to ServiceNow JSON",
          description: "Apply field mappings, date formats, and lookups.",
          position: { x: 740, y: 120 },
        },
        {
          id: "post-servicenow",
          type: "connector",
          label: "Post staging API",
          description: "Call ServiceNow table/batch API.",
          position: { x: 1010, y: 120 },
        },
        {
          id: "write-evidence",
          type: "connector",
          label: "Write evidence CSV",
          description: "Persist all record outcomes to SharePoint.",
          position: { x: 1280, y: 120 },
        },
        {
          id: "notify-error",
          type: "notify",
          label: "Notify errors",
          description: "Send file-level or record-level error mail.",
          position: { x: 740, y: 330 },
        },
        {
          id: "end",
          type: "end",
          label: "Archive source file",
          description: "Move processed TSV to BAK folder.",
          position: { x: 1540, y: 120 },
        },
      ],
      edges: [
        { id: "e1", source: "start", target: "read-sharepoint" },
        { id: "e2", source: "read-sharepoint", target: "validate-file" },
        { id: "e3", source: "validate-file", target: "map-servicenow", label: "valid" },
        { id: "e4", source: "validate-file", target: "notify-error", label: "invalid" },
        { id: "e5", source: "map-servicenow", target: "post-servicenow" },
        { id: "e6", source: "post-servicenow", target: "write-evidence" },
        { id: "e7", source: "write-evidence", target: "end" },
        { id: "e8", source: "post-servicenow", target: "notify-error", label: "validation errors" },
      ],
    },
  ],
  fmdSections: [
    {
      id: "fmd-log",
      title: "Document Log",
      sectionType: "documentLog",
      sortOrder: 1,
      content: {
        rows: [
          {
            date: "2026-05-20",
            name: "Boomi Architecture Team",
            version: "1.0",
            revision: "0",
            change: "Created from Boomi Helper Suite MVP sample project.",
          },
        ],
      },
    },
    {
      id: "fmd-overview",
      title: "Integration Overview",
      sectionType: "overview",
      sortOrder: 2,
      content: {
        summary:
          "SharePoint source TSV is validated, mapped to ServiceNow JSON, posted via REST, and evidence/error files are written back to SharePoint.",
        schedule: "Mon-Fri 14:00 and 16:30",
      },
    },
    {
      id: "fmd-env",
      title: "Environment Information",
      sectionType: "environment",
      sortOrder: 3,
      content: {
        boomiEnvironments: ["ESB-QA", "ESB-PRD"],
        network: "Boomi runtime IP ranges and ServiceNow/SharePoint allowlists managed outside the app.",
      },
    },
    {
      id: "fmd-job",
      title: "Job Setting and Error Handling",
      sectionType: "jobHandling",
      sortOrder: 4,
      content: {
        schedule: "Process Scheduler",
        retryPolicy: "Retry connector failures twice with five-minute interval.",
        notifications: "Mail notification for file-level and record-level failures.",
      },
    },
  ],
  boomiConnections: [
    {
      id: "boomi-mock",
      accountId: "MOCK-ACCOUNT",
      environmentName: "Sandbox mock",
      baseUrl: "https://api.boomi.com",
      authMode: "Basic API Token",
      apiUsername: "mock-username",
      apiPassword: "mock-password",
      mode: "mock",
      createdAt: "2026-05-20T09:00:00.000Z",
    },
  ],
  boomiDrafts: [
    {
      id: "draft-map",
      componentId: "mock-map-001",
      componentType: "transform.map",
      componentName: "Map - PO_SEIREN TSV to ServiceNow JSON",
      templateXml:
        '<bns:Component type="transform.map" name="Map - Template"><bns:object><Map/></bns:object></bns:Component>',
      proposedXml:
        '<bns:Component type="transform.map" name="Map - PO_SEIREN TSV to ServiceNow JSON"><bns:object><Map trackedFields="9" quality="review"/></bns:object></bns:Component>',
      diff: `- <bns:Component type="transform.map" name="Map - Template">
 + <bns:Component type="transform.map" name="Map - PO_SEIREN TSV to ServiceNow JSON">
 - <Map/>
 + <Map trackedFields="9" quality="review"/>`,
      validationStatus: "Dry-run valid",
      notes:
        "Safe to preview only. Real publish requires exporting the map template from the target Boomi account.",
      createdAt: "2026-05-20T09:00:00.000Z",
      updatedAt: "2026-05-20T09:00:00.000Z",
    },
    {
      id: "draft-process",
      componentId: "mock-process-001",
      componentType: "process",
      componentName: "Process - SRSN001 Seiren order intake",
      proposedXml:
        '<bns:Component type="process" name="Process - SRSN001 Seiren order intake"><bns:object><process dryRun="true"/></bns:object></bns:Component>',
      diff: "+ New process draft generated from flow designer.",
      validationStatus: "Needs template",
      notes:
        "Process XML must be created from an exported skeleton before sandbox publishing.",
      createdAt: "2026-05-20T09:00:00.000Z",
      updatedAt: "2026-05-20T09:00:00.000Z",
    },
  ],
};
